// Code generated by entc, DO NOT EDIT.

package tag

const (
	// Label holds the string label denoting the tag type in the database.
	Label = "tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeTagItems holds the string denoting the tag_items edge name in mutations.
	EdgeTagItems = "tag_items"
	// Table holds the table name of the tag in the database.
	Table = "tags"
	// TagItemsTable is the table that holds the tag_items relation/edge. The primary key declared below.
	TagItemsTable = "tag_tag_items"
	// TagItemsInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	TagItemsInverseTable = "items"
)

// Columns holds all SQL columns for tag fields.
var Columns = []string{
	FieldID,
	FieldTitle,
}

var (
	// TagItemsPrimaryKey and TagItemsColumn2 are the table columns denoting the
	// primary key for the tag_items relation (M2M).
	TagItemsPrimaryKey = []string{"tag_id", "item_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
