// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
